FROM almalinux:8
ADD https://raw.githubusercontent.com/techworldwithsiva/docker-install-commands/master/docker-install.sh /tmp/docker.sh
ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.76/bin/apache-tomcat-9.0.76.tar.gz /tmp/
RUN tar -xzvf /tmp/apache-tomcat-9.0.76.tar.gz/ /opt